apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2019-07-11T22:03:24Z"
  generation: 2
  labels:
    app: hack-deployments
  name: hack-deployments
  namespace: default
  resourceVersion: "3631"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/hack-deployments
  uid: b44b30c4-a427-11e9-aff4-5e3f56b1012b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hack-deployments
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hack-deployments
    spec:
      containers:
      - image: us.icr.io/hackregistry/hack:latest
        imagePullPolicy: IfNotPresent
        name: hack
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-07-11T22:31:35Z"
    lastUpdateTime: "2019-07-11T22:31:35Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-07-11T22:30:53Z"
    lastUpdateTime: "2019-07-11T22:31:35Z"
    message: ReplicaSet "hack-deployments-588dffc5b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1